# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  branch = "master"
  name = "github.com/appscode/go"

[[constraint]]
  branch = "release-8.0"
  name = "github.com/appscode/kutil"

[[constraint]]
  name = "github.com/appscode/osm"
  version = "0.7.1"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "=v1.12.7"

[[constraint]]
  name = "github.com/ghodss/yaml"
  version = "=1.0.0"

[[constraint]]
  name = "github.com/go-openapi/spec"
  version = "0.15.0"

[[constraint]]
  branch = "master"
  name = "github.com/graymeta/stow"
  source = "github.com/appscode/stow"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.11.3"

[[override]]
  name = "k8s.io/apimachinery"
  branch = "release-1.11.3"
  source = "github.com/pharmer/apimachinery"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.11.3"

[[override]]
  name = "k8s.io/kube-openapi"
  revision = "91cfa479c814065e420cee7ed227db0f63a5854e"

[prune]
  go-tests = true
  unused-packages = true
